Close_BTN='//div[@class="px-1   flex flex-middle nmx-1 pb-1"]'
TRIPTYPE_OPTION='//div[@class="p-relative"]//button'
RT_OPTION='//li[@value="rt"]'
WHERE_FROM='//input[@placeholder="Where from?"]'
FROM_CITY='//ul[@class="airportList"]//p[contains(text(),"Bangalore, IN - Kempegowda International Airport (BLR)")]'
WHERE_TO='//input[@placeholder="Where to?"]'
TO_CITY='//ul[@class="airportList"]//p[contains(text(),"New Delhi, IN - Indira Gandhi Airport (DEL)")]'
CALENDAR='//div[@class="flex flex-middle p-relative homeCalender"]//button[1]'
SEARCH='//div//span[contains(text(),"Search flights")]'
ele_toscroll='//div[@class="container pl-0 pr-0 c-pointer"]'
CAL_BOX='//div[@class="DayPicker w-100p"]'

